# Generated by Django 3.0.6 on 2020-06-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_auto_20200608_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttype',
            name='price_max',
            field=models.CharField(help_text='The price of the type.  The unit is in VND.  9 characters or fewer.', max_length=9, verbose_name='Maximum object type price'),
        ),
    ]
