# Generated by Django 3.0.6 on 2020-06-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_auto_20200611_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_objecttype',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Transaction - ObjectType quantity.  4 characters or fewer.', max_digits=6, verbose_name='Quantity'),
        ),
    ]
