# Generated by Django 3.0.6 on 2020-06-16 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_auto_20200612_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_type', models.TextField(verbose_name='Public record grouped by type')),
                ('by_month', models.TextField(verbose_name='Public record grouped by month')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2020, 6, 16, 14, 52, 39, 491005, tzinfo=utc), verbose_name='Time added')),
            ],
        ),
    ]
