# Generated by Django 3.0.6 on 2020-06-16 14:59

import collect.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_publicrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrecord',
            name='by_type',
            field=models.TextField(default=collect.models.Transaction_ObjectType.get_public_by_type, verbose_name='Public record grouped by type'),
        ),
        migrations.AlterField(
            model_name='publicrecord',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 14, 59, 3, 413373, tzinfo=utc), verbose_name='Time added'),
        ),
    ]
