# Generated by Django 3.0.6 on 2020-06-16 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0008_auto_20200616_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrecord',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 15, 7, 13, 741047, tzinfo=utc), verbose_name='Time added'),
        ),
    ]
