# Generated by Django 3.0.6 on 2020-06-22 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200622_1707'),
        ('collect', '0011_auto_20200616_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='submitted_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Location'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='detail_address',
            field=models.CharField(blank=True, help_text='Required for collections. 256 characters or fewer.', max_length=256, verbose_name='Detail address'),
        ),
    ]
