# Generated by Django 3.0.6 on 2020-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0012_auto_20200622_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_objecttype',
            name='quantity',
            field=models.IntegerField(help_text='Transaction - ObjectType quantity.', verbose_name='Quantity'),
        ),
    ]
