# Generated by Django 3.0.6 on 2020-06-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='detail_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
