# Generated by Django 3.0.6 on 2020-06-30 04:43

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200623_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Vietnamese phone number only e.g: +84 999999999, +84999999999 or 0999999999', max_length=16, validators=[accounts.validators.PhoneNumberValidator()], verbose_name='Phone number'),
        ),
    ]
