# Generated by Django 3.0.6 on 2020-07-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200630_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the day', max_length=15, verbose_name='Name of the day')),
                ('isoday', models.IntegerField(verbose_name='ISO Weekday')),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
                'db_table': 'Week',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='collecting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Collecting time'),
        ),
        migrations.AddField(
            model_name='user',
            name='collecting_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Day', verbose_name='The day to collect weekly'),
        ),
    ]
