# Generated by Django 3.0.6 on 2020-06-08 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the object type.  256 characters or fewer.', max_length=256, verbose_name='Object type name')),
                ('price', models.CharField(help_text='The price of the type.  The unit is in VND.  9 characters or fewer.', max_length=9, verbose_name='Object type price')),
                ('unit', models.CharField(help_text='The unit of the object type.  256 characters or fewer.', max_length=256, verbose_name='Object type unit')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted date')),
                ('collecting_date', models.DateTimeField(verbose_name='Collecting date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active transaction? Required.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(help_text='Transaction - ObjectType quantity.  4 characters or fewer.', max_length=4, verbose_name='Quantity')),
                ('objecttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_objecttype', to='collect.ObjectType')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_objecttype', to='collect.Transaction')),
            ],
        ),
    ]
