# Generated by Django 3.0.6 on 2020-06-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objecttype',
            name='price',
        ),
        migrations.AddField(
            model_name='objecttype',
            name='price_max',
            field=models.CharField(default=0, help_text='The price of the type.  The unit is in VND.  9 characters or fewer.', max_length=9, verbose_name='Maximun object type price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objecttype',
            name='price_min',
            field=models.CharField(default=0, help_text='The price of the type.  The unit is in VND.  9 characters or fewer.', max_length=9, verbose_name='Minimum object type price'),
            preserve_default=False,
        ),
    ]
