# Generated by Django 3.0.6 on 2020-06-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20200608_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objecttype',
            old_name='name',
            new_name='type_name',
        ),
    ]
